// JavaScript Document
var M=2;
var NN=2;
function change(N)
{
	if(M >= 20)
	{
		M=N;
		$("#RJ").removeClass("RJ");
		$("#XJ").removeClass("XJ");
		$("#TD").removeClass("TD");
		$("#LP").removeClass("LP");
		$("#QD").removeClass("QD");
		$("#JY_1").removeClass("JY_1");
		$("#JY_2").removeClass("JY_2");
		$("#SD").removeClass("SD");
		$("#JS_1").removeClass("JS_1");
		$("#JS_2").removeClass("JS_2");
		$("#HL").removeClass("HL");
		$("#DDH").removeClass("DDH");
		$("#LD").removeClass("LD");
		$("#LHK_1").removeClass("LHK_1");
		$("#LHK_2").removeClass("LHK_2");
		$("#MEG_1").removeClass("MEG_1");
		$("#MEG_2").removeClass("MEG_2");
		$("#BZ").removeClass("BZ");
		$("#BX").removeClass("BX");
		$("#EJ").removeClass("EJ");
		$("#LZK").removeClass("LZK");
		$("#ZL").removeClass("ZL");
		$("#WQZ").removeClass("WQZ");
		add();
		M=20;
	}else if(N > M)
	{
		alert("请走完上一步");
	}
	else if(N < M)
	{
		alert("上一征程已结束");
	}
	else
	{
		add();
		M=M+1;
		NN=M;
	}
	
}
function add()
{
	if(M==2)
		{
			$("#RJ").removeClass("RJ");
			$("#XJ").addClass("XJ");
			$(".nav_t").css("left","-1015px");
		}
		if(M==3)
		{
			$("#XJ").removeClass("XJ");
			$("#TD").addClass("TD");
			$(".nav_t").css("left","-955px");
		}
		if(M==4)
		{
			$("#TD").removeClass("TD");
			$("#LP").addClass("LP");
			$(".nav_t").css("left","-895px");
		}
		if(M==5)
		{
			$("#LP").removeClass("LP");
			$("#QD").addClass("QD");
			$(".nav_t").css("left","-835px");
		}
		if(M==6)
		{
			$("#QD").removeClass("QD");
			$("#JY_1").addClass("JY_1");
			$("#JY_2").addClass("JY_2");
			
			$(".nav_t").css("left","-775px");
		}
		if(M==7)
		{
			$("#JY_1").removeClass("JY_1");
			$("#JY_2").removeClass("JY_2");
			$("#SD").addClass("SD");
			$(".nav_t").css("left","-715px");
		}
		if(M==8)
		{
			$("#SD").removeClass("SD");
			$("#JS_1").addClass("JS_1");
			$("#JS_2").addClass("JS_2");
			$(".nav_t").css("left","-655px");
		}
		if(M==9)
		{
			$("#JS_1").removeClass("JS_1");
			$("#JS_2").removeClass("JS_2");
			$("#HL").addClass("HL");
			$(".nav_t").css("left","-595px");
		}
		if(M==10)
		{
			$("#HL").removeClass("HL");
			$("#DDH").addClass("DDH");
			$(".nav_t").css("left","-535px");
		}
		if(M==11)
		{
			
			$("#DDH").removeClass("DDH");
			$("#LD").addClass("LD");
			$(".nav_t").css("left","-475px");
		}
		if(M==12)
		{
			$("#LD").removeClass("LD");
			$("#LHK_1").addClass("LHK_1");
			$("#LHK_2").addClass("LHK_2");
			$(".nav_t").css("left","-415px");
		}
		if(M==13)
		{
			$("#LHK_1").removeClass("LHK_1");
			$("#LHK_2").removeClass("LHK_2");
			$("#MEG_1").addClass("MEG_1");
			$("#MEG_2").addClass("MEG_2");
			$(".nav_t").css("left","-355px");
		}
		if(M==14)
		{
			$("#MEG_1").removeClass("MEG_1");
			$("#MEG_2").removeClass("MEG_2");
			$("#BZ").addClass("BZ");
			$(".nav_t").css("left","-295px");
		}
		if(M==15)
		{
			$("#BZ").removeClass("BZ");
			$("#BX").addClass("BX");
			$(".nav_t").css("left","-235px");
		}
		if(M==16)
		{
			$("#BX").removeClass("BX");
			$("#EJ").addClass("EJ");
			$(".nav_t").css("left","-175px");
		}
		if(M==17)
		{
			$("#EJ").removeClass("EJ");
			$("#LZK").addClass("LZK");
			$(".nav_t").css("left","-115px");
		}
		if(M==18)
		{
			$("#LZK").removeClass("LZK");
			$("#WQZ").addClass("WQZ");
			$(".nav_t").css("left","-55px");
		}
		if(M==19)
		{
			$("#WQZ").removeClass("WQZ");
			$("#ZL").addClass("ZL");
			$(".nav_t").css("left","0px");
		}
}

function N_change(NN){
	change(NN);
	NN++;
}
